jobs:
  build:
    runs-on: ubuntu-latest   # build on GitHub cloud runner
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: chanchalpiyushsharma/flask-devops-app:latest

  deploy:
    runs-on: self-hosted     # 🚀 runs on your laptop
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Update Deployment & Restart
        run: |
          # ✅ ensure imagePullPolicy is Always
          kubectl patch deployment flask-app -p '{"spec":{"template":{"spec":{"containers":[{"name":"flask-container","imagePullPolicy":"Always"}]}}}}'

          # ✅ update image
          kubectl set image deployment/flask-app flask-container=chanchalpiyushsharma/flask-devops-app:latest

          # ✅ restart pods to force new image pull
          kubectl rollout restart deployment flask-app
          kubectl rollout status deployment flask-app

